### ISSUE TITLE
Cookies parameter Error

### ISSUE THREAD

**Issue by dejvidecz** [gaboe/rest2ts#60]
When I use rest2ts with --cookies parameter it adds credentials attribute to requestOptions:
![image](https://github.com/gaboe/rest2ts/assets/10745725/f003407d-7a3a-4d15-8550-2954bc443de5)

But defined type is:
![image](https://github.com/gaboe/rest2ts/assets/10745725/1302eac1-86c8-4afa-bf3e-67a9da332af3)

**Comment by gaboe** [comment]
Fixed at v5.1.10
