### ISSUE TITLE
Generate error in version 5.1.11

### ISSUE THREAD

**Issue by dejvidecz** [gaboe/rest2ts#61]
Since version 5.1.11 - generator does not work.
![image](https://github.com/gaboe/rest2ts/assets/10745725/3f60236b-cdeb-474e-8f1c-9214b4c0165d)

swagger.json:
[swagger.json](https://github.com/user-attachments/files/15753447/swagger.json)

Version 5.1.10 works without problem.

**Comment by gaboe** [comment]
Thx for report. 

Fixed by.
https://github.com/gaboe/rest2ts/commit/f0acff814a880823aec2673ef5f5d701794db993

Fixed at version 5.1.12
