### ISSUE TITLE
multipart/form-data support

### ISSUE THREAD

**Issue by dejvidecz** [gaboe/rest2ts#62]
Is it possible to add support for multipart/form-data with json content?

Swagger example:

[swagger.json](https://github.com/user-attachments/files/15776495/swagger.json)

Expected behavior after generating - something like this:
<img width="1661" alt="image" src="https://github.com/gaboe/rest2ts/assets/10745725/44b5be32-6f13-4d88-8144-41bea4419429">

Generated behaviour - DTO is completely missing.
<img width="1640" alt="image" src="https://github.com/gaboe/rest2ts/assets/10745725/4a28840c-99fc-4747-b599-9e56b10345d4">

I woud use something like Generic FormData for this - maybe this https://github.com/microsoft/TypeScript/issues/43797#issuecomment-1311633838

And result should be request that looks like this:
<img width="395" alt="image" src="https://github.com/gaboe/rest2ts/assets/10745725/5c30f60c-0277-4f57-871b-d2d869a79f19">

What do you think? :)

**Comment by gaboe** [comment]
Good idea to add this. 

What is IRuntimeForm? Is it imported from somewhere?

**Comment by dejvidecz** [comment]
@gaboe 
Just something i found here as example:
https://github.com/microsoft/TypeScript/issues/43797#issuecomment-903975155

**Comment by gaboe** [comment]
Ok, I wasn't sure if it comes from some package. It looks good - are you working on implementation? I can implement when i would have a time.

**Comment by dejvidecz** [comment]
@gaboe 
Maybe i have found easier solution.
For multipart/form-data just use same functions but update post request like this:
<img width="1667" alt="image" src="https://github.com/gaboe/rest2ts/assets/10745725/69620c02-3b8a-4604-890a-c69d24afa207">

What do you think? (Its not tested solution - just idea)
Does it make sense to you?

**Comment by dejvidecz** [comment]
@gaboe 
https://github.com/gaboe/rest2ts/pull/63
